server:
    port: 8081
    session:
        timeout: -1
    tomcat:
        uri-encoding: UTF-8

# 配置mybatis-plus
mybatis-plus:
    # 配置扫描xml
    mapper-locations: classpath:mapper/*.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.jiang.entity
    global-config:
        # 逻辑删除配置
        logic-delete-value: 0
        logic-not-delete-value: 1
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

spring:
    datasource:
        name: jiangdb
        url: jdbc:mysql://localhost:3306/jiangdb
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

logging:
    level:
      com.jiang: DEBUG
      org.springframework.web: INFO